const express = require("express");
const reportController = require("../controller/reportController");
const auth = require("../middleware/auth");
const router = express.Router();

router.post("/reportFilterPurchaseGoods", auth, reportController.reportFilterPurchaseGoods);
router.post("/reportDownStreamVehicles", auth, reportController.reportDownStreamVehicles);
router.post("/reportUpStreamVehicles", auth, reportController.reportUpStreamVehicles);
router.post("/reportFranchiseEmission", auth, reportController.reportFranchiseEmission);
router.post("/reportInvestmentEmission", auth, reportController.reportInvestmentEmission);
router.post("/reportStationaryCombustion", auth, reportController.reportStationaryCombustion);
router.post("/reportUpstreamLeaseEmission", auth, reportController.reportUpstreamLeaseEmission);
router.post("/reportDownstreamLeaseEmission", auth, reportController.reportDownstreamLeaseEmission);
router.post("/reportWasteGeneratedEmission", auth, reportController.reportWasteGeneratedEmission);
router.post("/reportFlightTravel", auth, reportController.reportFlightTravel);
router.post("/reportOtherTransport", auth, reportController.reportOtherTransport);
router.post("/reportHotelStays", auth, reportController.reportHotelStays);
router.post("/reportEmployeeCommuting", auth, reportController.reportEmployeeCommuting);
router.post("/reportHomeOffice", auth, reportController.reportHomeOffice);
router.post("/reportSoldProducts", auth, reportController.reportSoldProducts);
router.post("/reportEndOfLifeTreatment", auth, reportController.reportEndOfLifeTreatment);
router.post("/reportProOfSoldProducts", auth, reportController.reportProOfSoldProducts);
router.post("/reportRegfriegrant", auth, reportController.reportRegfriegrant);
router.post("/reportFireExtinguisher", auth, reportController.reportFireExtinguisher);
router.post("/reportRenewableElectricity", auth, reportController.reportRenewableElectricity);
router.post("/reportHeatandSteam", auth, reportController.reportHeatandSteam);
router.post("/reportWaterSupplyandTreatment", auth, reportController.reportWaterSupplyandTreatment);
router.post("/reportCompanyOwnedVehicles", auth, reportController.reportCompanyOwnedVehicles);
router.post("/reportFilterMultipleCategory", reportController.reportFilterMultipleCategory);
router.post("/reportFilterMultipleCategoryNew", reportController.reportFilterMultipleCategoryNew);
router.post("/reportFilterMultipleCategoryConsolidated", reportController.reportFilterMultipleCategoryConsolidated);
router.post("/waterReport", reportController.waterReport);
router.post("/waterReportConsolidated", reportController.waterReportConsolidated);
router.post("/reportFilterMultipleCategoryAudit", reportController.reportFilterMultipleCategoryAudit);
router.post("/vendorReport", reportController.vendorReport);
router.post("/vendorDashboardReport", reportController.vendorDashboardReport);
router.post("/getEmisionByLocation", auth, reportController.getEmisionByLocation);
router.post("/getVendorProductDashboard", auth, reportController.getVendorProductDashboard);

module.exports = router;